# Site
name: "Journal for Wellbeing"
title: "Journal for Wellbeing"
description: "..."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
url: "https://journalforwellbeing.com"
baseurl: ""
lang: en-US
timezone: UTC
twitter_username: journalwell
author: "Journal for Wellbeing"
social:
  links:
    - https://twitter.com/journalwell
    - https://mastodon.social/@journalwell
google_analytics: 'G-QS47EGNW5T'
disqus: 'journalforwellbeing'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  elias:
    name: Elias
    display_name: Elias
    gravatar: 
    email: 
    web: 
    twitter: 
    description: "Writes quietly on the practice of self-inquiry, inner stillness, and the slow unfolding of personal insight."

  maren:
    name: Maren
    display_name: Maren
    gravatar: 
    email: 
    web: 
    twitter: 
    description: "Explores the gentle intersection of journaling, emotional care, and the small rituals that help us feel more at home in ourselves."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-6236889265406066"
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, docker-compose.yml, site/]

# Show or hide future-dated posts, author, etc.,
future: false
show_author_box: false

sass:
  style: compressed
