# Site
name: "Journal for Wellbeing"
title: "Journal for Wellbeing"
description: "A quiet online journal exploring mindfulness, emotional well-being, and the healing power of writing."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
url: "https://journalforwellbeing.com"
baseurl: ""
lang: en-US
timezone: UTC
twitter_username:
author: "Journal for Wellbeing"
social:
  links:
    - #
    - #
disqus: 'journalforwellbeing'
include:
  - _pages
  - _redirects
permalink: /:title/

# Authors
authors:
  solenya:
    name: Solenya
    display_name: Solenya
    gravatar:
    email:
    web:
    twitter:
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-redirect-from
  - jekyll-include-cache

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense
adsense: "enabled"
adsense-data-ad-client: "ca-pub-6236889265406066"
adsense-data-ad-slot: "9525717750"

# Lazy Images
lazyimages: "enabled"

# Build exclusions
exclude:
  - changelog.md
  - LICENSE.txt
  - README.md
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - site/

# Misc
future: false
show_author_box: false

sass:
  style: compressed
  sass_dir: _sass

